config/routes.rb
Rails.application.routes.draw do
  root to: "homepages#index"

  resources :homepages, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :transactions, only: [:index]
  resources :users, only: [:create]

  get "/logout" => "sessions#destroy", as: "logout"
end

app/models/bankaccount.rb
class Bankaccount < ActiveRecord::Base
  belongs_to :user
  has_many :transactions

  validates :balance, numericality: {greater_than_or_equal_to: 0.0}
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :bankaccount
  belongs_to :foreign_bankaccount, class_name: "Bankaccount"

  validates :amount, presence: true

  validate :amount_may_not_be_zero

  after_save :update_balance

  private

  def update_balance
    bankaccount.update_attribute :balance, bankaccount.transactions.sum(:amount)
  end

  def amount_may_not_be_zero
    if amount == 0.0
      errors.add(:amount, I18n.t(".activerecord.errors.models.transaction.attributes.amount"))
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :bankaccount
  has_many :transactions, through: :bankaccount

  validates :bankaccount, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  # Code used: http://stackoverflow.com/questions/13784845/how-would-one-validate-the-format-of-an-email-field-in-activerecord
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  has_secure_password

  before_validation :new_bankaccount
  validate :password_match_password_confirmation

  # You need to reload the bankaccount to get the actual balance
  def current_balance
    "EUR. #{sprintf('%.2f', bankaccount.reload.balance)}"
  end

  def deposit amount = nil
    # if the given param is a string, convert it to an integer
    amount = amount.to_d if amount.present?
    # check if amount is positive and if it is not zero
    if amount.blank? || amount == 0
      I18n.t("activerecord.messages.models.user.zero_deposit_not_allowed")
    elsif amount < 0
      I18n.t("activerecord.messages.models.user.negative_deposit_not_allowed")
    else
      translated_amount = sprintf('%.2f', amount)
      Transaction.create(bankaccount_id: bankaccount.id, amount: amount, 
        comment: I18n.t("activerecord.messages.models.user.deposit", amount: translated_amount))
      I18n.t("activerecord.messages.models.user.deposit_added", amount: translated_amount)
    end
  end

  def transfer_money bankaccount_id, amount, comment
    # if the given param is a string, convert it to an integer
    amount = amount.to_d if amount.present?
    # check if bankaccount is given
    if bankaccount_id.blank?
      I18n.t("activerecord.messages.models.user.no_bankaccount")
    # check if amount is positive
    elsif amount.blank? || amount == 0
      I18n.t("activerecord.messages.models.user.zero_transfer_not_allowed")
    elsif amount < 0
      I18n.t("activerecord.messages.models.user.negative_transfer_not_allowed")
    # check if amount is greater than balance
    elsif bankaccount.reload.balance < amount
      I18n.t("activerecord.messages.models.user.not_enough_balance")
    else
      translated_amount = sprintf('%.2f', amount)
      transferred_from = Bankaccount.find(bankaccount.id).user
      transferred_to = Bankaccount.find(bankaccount_id).user
      # Transaction 'Transferred from'
      Transaction.create(bankaccount_id: bankaccount.id, foreign_bankaccount_id: bankaccount_id, amount: -amount, comment: comment)

      # Transaction 'Transferred to'
      Transaction.create(bankaccount_id: bankaccount_id, foreign_bankaccount_id: bankaccount.id, amount: amount,  comment: comment)
      I18n.t("activerecord.messages.models.user.amount_transfered", amount: translated_amount, bankaccount_id: bankaccount_id, firstname: transferred_to.firstname, lastname: transferred_to.lastname)
    end
  end

  private
  def new_bankaccount
    self.bankaccount = Bankaccount.new if self.bankaccount.blank?
    true
  end

  # I do not know why, but it looks to be that the 'password_confirmation match' from has_secure_password does not work out-of-the-box
  # That is why I added this validation
  def password_match_password_confirmation
    if password != password_confirmation
      errors.add(:password_confirmation, I18n.t(".activerecord.errors.models.user.attributes.password_confirmation"))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  before_filter :authenticate

  def authenticate
    if session[:user_id].blank?
      flash[:notice] = I18n.t("controllers.application.not_logged_in")
      redirect_to new_session_path
    end
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
    @user = User.new

    # needed for the transfer form
    @bankaccounts = User.where.not(id: current_user.id).joins(:bankaccount).collect{|x| ["#{x.firstname} #{x.lastname} - #{t(".bankaccount")}: #{x.bankaccount.id}", x.bankaccount.id]}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate

  def new
    @user = User.new
    render "new"
  end

  def create
    user = User.where(email: params[:user][:email]).first
    if user.present? && user.authenticate(params[:user][:password])
      flash[:info] = t(".succesful_logged_in")
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = t(".invalid_username_password")
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = t(".succesful_logged_out")
    redirect_to new_session_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = current_user.transactions    
    flash[:info] = t(".no_transactions") if @transactions.empty?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    flash[:info] = case
      # called without 'present' to tigger the error message if no value givven, but the button is clicked
      when params[:user][:deposit] then current_user.deposit params[:user][:deposit]
      when params[:user][:transfer_money].present? 
        then current_user.transfer_money params[:user][:transfer_money][:bankaccount_id], params[:user][:transfer_money][:amount], params[:user][:transfer_money][:comment]
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end

  def current_path
    request.path
  end
end

app/views/homepages/index.html.slim
div.page-header
  h1= t(".deposit_amount")

.deposit-form
  = simple_form_for @user do |f|
    = f.input :deposit, input_html: {placeholder: "0.00", value: nil}, required: true
    = f.submit t(".deposit_now"), class: "btn btn-primary"

div.page-header
  h1= t(".transfer_money")
.transfer-form
  = simple_form_for @user do |f|
    = f.simple_fields_for :transfer_money do |f|
      = f.input :bankaccount_id, collection: @bankaccounts, label: t(".bankaccount")
      = f.input :amount, input_html: {placeholder: "0.00", value: nil}, label: t(".amount")
      = f.input :comment, input_html: {value: nil}, label: t(".comment"), required: false
      = f.submit t(".transfer_now"), class: "btn btn-primary"

hr

app/views/layouts/application.html.slim
doctype html
html
  head
    title= t(".title")
    meta name="keywords" content="template language"
    meta name="author" content="author"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container
      // flash_mmessages
      - if flash[:info].present?
        .alert.alert-info= flash[:info]
      - if flash[:notice].present?
        .alert.alert-warning= flash[:notice]
      - if flash[:error].present?
        .alert.alert-danger= flash[:error]

      h1= t(".welcome_to_ruby_bank")

      - if current_user.present?
        // navbar
        nav.navbar
          ul.navbar-nav.nav
            li= link_to t(".home"), root_path, class: current_path == root_path ? "btn btn-default active" : "btn btn-default"
            li= link_to t(".transactions"), transactions_path, class: current_path == transactions_path ? "btn btn-default active" : "btn btn-default"

      - if current_user.present?
        div.page-header
          h1= t(".balance_info")

        div.well
          p.balance= UserPresenter.new(current_user).current_balance

      = yield

      - if current_user.present?
        div
          p= link_to t(".logout"), logout_path, class: "btn btn-primary"

app/views/transactions/index.html.slim
- if !@transactions.empty?
  div.page-header
    p
      h2= t(".transactions")

  div
    table.table
      tr
        th= t(".amount")
        th= t(".comment")
        th= t(".created_at")
        th= t(".foreign_bankaccount_number")
        th= t(".foreign_bankaccount_name")
      - @transactions.each do |transaction|
        tr
          td= TransactionPresenter.new(transaction).amount
          td= transaction.comment
          td= TransactionPresenter.new(transaction).created_at
          td= TransactionPresenter.new(transaction).foreign_bankaccount_number
          td= TransactionPresenter.new(transaction).foreign_bankaccount_name